application:
  cryptocurrency-information-api:
    url: https://api.coinlore.net/api/
  queues:
    coin-url: 'aws2-sqs://teste2-queue?amazonSQSClient=#sqsClient&concurrentConsumers=1&maxMessagesPerPoll=10'

pool:
  cryptocurrency-information-api:
    maxConn: 20
    maxRoutes: 200
    connTimeout: 60000
    readTimeout: 60000

camel:
  component:
    aws2-sqs:
      enabled: true
      proxy-host: 'sqs.us-west-2.amazonaws.com'
      proxy-port: 80
      region: 'us-west-2'
      protocol: 'http'